version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - aws s3 cp s3://clmw-api-hosting/application.yml ./src/main/resources/application.yml
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - mv target/project2_api-1.0-SNAPSHOT.jar CLMW_api_p2

artifacts:
  files:
    - project2_api-1.0-SNAPSHOT.jar