server:
  port: 5000
  servlet:
    context-path: /teaManager

spring:
  application:
    name: team-manager
  data:
    mongodb:
      host: 3.143.144.114
      port: 27017
      database: project2
      username: revature
      password: team

encrypt:
  salt: potato

jwt:
  header: Authorization
  prefix: Bearer
  secret: Reavture
  expiration: 86400000
